#!/bin/sh
# Sample OGG/MP3 player wrapper
# Intended for use with jinamp, but could be used for anything

# This script is in the public domain; do what you like with it

# It is important to `exec' the player because jinamp keeps track of the PID
# of the player, so if it isn't exec'ed then this shell would receive signals
# and not the player

PATH=/bin:/usr/bin:/usr/local/bin

# Check that we have an argument
if [ $# -lt 1 ]; then
 echo "Usage: playaudio <filename>"
 exit 1
fi

# Displays the song info on tty10
if echo "x$1" | grep '\.mp3$' > /dev/null; then
  id3 -l -- "$1" | head -n 2 | tail -n 1 > /dev/tty10
  exec mpg123 -b 32 -q -- "$1"
elif echo "x$1" | grep '\.ogg$' > /dev/null; then
  vorbiscomment "$1" | awk -F= '/^[Tt]itle/{title=$2}/^[Aa]rtist/{artist=$2}\
                            END{printf "Title: %-32s Artist: %s\n", title, artist;}' > /dev/tty10
  exec ogg123 -b 32 -q -- "$1"
fi
